<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="11.0" Width="2" Height="1.25" GapLength="0.0625" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="1" LabelsHorizontalGapLength="0" IsContinuous="False" PrintSpeed="" PrintMirror="False" CutAfterPrinting="False" BatchCut="1">
  <Items>
    <TextItem X="0.0807" Y="0.0947" DataField="PackingListID" Expression="_x0022_ITEM_x0020__x0023__x0020__x0022__x0020__x002B__x0020__x005B_DataFields_x0021_PackingListID_x005D__x002B__x0022_-_x0022__x002B__x005B_DataFields_x0021_PackingListItemID_x005D_" Width="1.803" Height="0.2844" Text="_x0031_245-1" BorderThickness="0,0.01,0,0.01" Font="ZPL Font A,16,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Center" />
    <TextItem X="0.8002" Y="0.8327" Expression="_x005B_DataFields_x0021_ItemQnty_x005D__x002B__x0022__x0020_of_x0020__x0022__x0020__x002B__x005B_DataFields_x0021_ItemCount_x005D_" Width="1.0741" Height="0.3047" Text="Type_x0020_here" Font="ZPL Font A,14,Point,,,False,90,,CP850" TextAlignment="Center" />
    <TextItem X="0.0691" Y="0.4465" DataField="ItemQnty" Width="0.7086" Height="0.6909" Text="_x0031_" BorderThickness="0.02" CornerRadius="0.06" Font="ZPL Font 0,32,Point,,,False,90,,CP850" TextAlignment="Center" />
  </Items>
</ThermalLabel>