<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="11.0" Width="1.25" Height="0.875" GapLength="0.0625" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="1" LabelsHorizontalGapLength="0" IsContinuous="False" PrintSpeed="" PrintMirror="False" CutAfterPrinting="False" BatchCut="1">
  <Items>
    <BarcodeItem X="0.0781" Y="0.528" DataField="PackingListID" Width="1.0833" Height="0.2804" Symbology="Code128" Code="_x0031_23456789" AddChecksum="False" BarcodeAlignment="MiddleCenter" DisplayCode="False" Font="NativePrinterFontA,5,Point,,,False,90,,CP850" Sizing="FitProportional" TextFont="NativePrinterFontA,10,Point,,,False,90,,CP850" MaxiCodeDrawPixelBasedSymbol="True" DotCodeAspectRatio="" />
    <TextItem X="0.0674" Y="0.0814" DataField="PackingListID" Width="1.1138" Height="0.1891" Text="Type_x0020_here" Font="ZPL Font A,9,True,False,False,False,Point,,,False,90,,CP850" TextAlignment="Center" />
    <TextItem X="0.071" Y="0.3261" Expression="_x005B_DataFields_x0021_Pieces_x005D__x002B__x0022__x0020_of_x0020__x0022__x0020__x002B__x005B_DataFields_x0021_Count_x005D_" Width="1.1073" Height="0.177" Text="Type_x0020_here" Font="ZPL Font A,5,Point,,,False,90,,CP850" TextAlignment="Center" />
  </Items>
</ThermalLabel>