<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="11.0" Width="4" Height="2" GapLength="0" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="1" LabelsHorizontalGapLength="0" IsContinuous="False" PrintSpeed="" PrintMirror="False" CutAfterPrinting="False" BatchCut="1">
  <Items>
    <RectangleShapeItem Width="4" Height="2" StrokeThickness="0.03" />
    <TextItem Name="GTIN" X="0.1459" Y="1.9087" Width="1.5105" Height="0.2396" Text="_x0028_01_x0029__x0020_10850510002011" Font="ZPL Font 0,12,Point,,,False,90,,CP850" />
    <TextItem Name="Lot" X="0.1355" Y="2.1796" Width="1.5209" Height="0.2396" Text="_x0028_10_x0029__x0020_46587443HG234" Font="ZPL Font 0,12,Point,,,False,90,,CP850" />
    <TextItem X="0.0938" Y="0.1561" Width="1.8543" Height="0.6668" Text="DESIGN_x0020_SYNTHESIS_x002C_INC_x000D__x000A_9855_x0020_Black_x0020_Mountain_x0020_Rd_x000D__x000A_San_x0020_Diego_x002C__x0020_Ca_x0020_92127" Font="ZPL Font 0,12,Point,,,False,90,,CP850" TextAlignment="Center" />
    <BarcodeItem X="0.0938" Y="1.1421" Expression="_x0022__x0028_01_x0029__x0022__x0020__x002B__x0020_Right_x0028__x005B_Items_x0021_GTIN_x005D__x002C__x0020_Len_x0028__x005B_Items_x0021_GTIN_x005D__x0029__x0020_-_x0020_5_x0029__x0020__x002B__x0020__x0022__x0028_10_x0029__x0022__x0020__x002B__x0020_Right_x0028__x005B_Items_x0021_Lot_x005D__x002C__x0020_Len_x0028__x005B_Items_x0021_Lot_x005D__x0029__x0020_-_x0020_5_x0029_" Width="3.7917" Height="0.6771" Symbology="GS1128" Code="_x0031_09344" AddChecksum="False" BarcodeAlignment="MiddleCenter" Font="NativePrinterFontA,5,Point,,,False,90,,CP850" Sizing="FitProportional" TextFont="NativePrinterFontA,10,Point,,,False,90,,CP850" MaxiCodeDrawPixelBasedSymbol="True" DotCodeAspectRatio="" />
    <LineShapeItem X="2.0012" Y="0.0208" Width="0.03" Height="0.9271" StrokeThickness="0.03" Orientation="Vertical" />
    <TextItem X="2.1888" Y="0.1982" Width="1.6667" Height="0.6668" Text="Capacitive_x0020_Switch_x0020_Driver_x000D__x000A_Firmware_x0020_Version_x0020_5.1_x0020_a_x000D__x000A_1_x002F_4_x002F_2023_x000D__x000A_PN:_x0020_109344_x0020_" Font="ZPL Font 0,9,Point,,,False,90,,CP850" TextAlignment="Center" />
    <LineShapeItem X="0.0212" Y="0.9212" Width="3.9688" Height="0.03" StrokeThickness="0.03" />
  </Items>
</ThermalLabel>