<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="11.0" Width="2.25" Height="1.25" GapLength="0.13" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="1" LabelsHorizontalGapLength="0" IsContinuous="False" PrintSpeed="" PrintMirror="False" CutAfterPrinting="False" BatchCut="1">
  <Items>
    <BarcodeItem X="0.1188" Y="0.6983" Width="1.9855" Height="0.491" Symbology="Code128" Code="_x0031_23456789" BarcodeAlignment="MiddleCenter" Font="NativePrinterFontA,5,Point,,,False,90,,CP850" Sizing="FitProportional" TextAlignment="BelowRight" TextFont="NativePrinterFontA,10,Point,,,False,90,,CP850" MaxiCodeDrawPixelBasedSymbol="True" DotCodeAspectRatio="" />
    <LineShapeItem X="0.0792" Y="0.6638" Width="2.0833" Height="0.01" />
    <TextItem X="0.1541" Y="0.1379" Width="1.9688" Height="0.1438" Text="Job_x0020_:_x0020_Yadohhilo" Font="NativePrinterFontA,7,False,False,False,True,Point,,,False,90,,CP850" />
  </Items>
</ThermalLabel>