// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class AssetClass
{
    public int AssetClassID { get; set; }

    public string AssetClassName { get; set; }

    public virtual Asset Asset { get; set; }
}