// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class Asset
{
    public int AssetID { get; set; }

    public string AssetName { get; set; }

    public string AssetDescription { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public int? PurchaseOrderID { get; set; }

    public int? ManuID { get; set; }

    public int? AssetClassID { get; set; }

    public decimal? PurchasePrice { get; set; }

    public int? SupplierID { get; set; }

    public string AddedBy { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DateAdded { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ManuPartNum { get; set; }

    public string Tag { get; set; }

    public string SerialNumber { get; set; }

    public int? LocationID { get; set; }

    public virtual AssetClass AssetNavigation { get; set; }
}