// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity
{
    public partial class Attachment
    {
        public int AttachmentID { get; set; }
        public string AttachmentDescription { get; set; }
        public int? PurchaseOrderID { get; set; }
        public string src { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
        public string FileSize { get; set; }
        public Guid RowID { get; set; }
        public byte[] BLOBData { get; set; }

        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}