// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class ClaimItem
{
    public int ClaimItemID { get; set; }

    public int? ClaimID { get; set; }

    public int? LineID { get; set; }

    public int? partID { get; set; }

    public string Bcode { get; set; }

    public string Description { get; set; }

    public int? TransActionType { get; set; }

    public int? ProductID { get; set; }

    public string DefectDescription { get; set; }

    public virtual ICollection<ClaimDocument> ClaimDocument { get; set; } = new List<ClaimDocument>();
}