// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class DeliveryReceipt
{
    public int DeliveryReceiptID { get; set; }

    public Guid FileGuid { get; set; }

    public int? PickListID { get; set; }

    public string ReferenceName { get; set; }

    public byte[] ReceiptImage { get; set; }
}