// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class Destination
{
    public int DestinationID { get; set; }

    public string DestinationName { get; set; }

    public string Attn { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public virtual Delivery Delivery { get; set; }
}