// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity
{
    public partial class DocumentParts
    {
        public int PartID { get; set; }
        public int DocID { get; set; }

        public virtual Document Doc { get; set; }
        public virtual Part Part { get; set; }
    }
}