// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class Employee
{
    public int employeeID { get; set; }

    public string firstname { get; set; }

    public string lastname { get; set; }

    public string middlename { get; set; }

    public bool? IsPurchaser { get; set; }

    public string EmployeeEmail { get; set; }

    public bool? Show { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual ICollection<PickList> PickList { get; set; } = new List<PickList>();

    public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; } = new List<PurchaseOrder>();
}