// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity
{
    public partial class Globals
    {
        public int GiD { get; set; }
        public string ElementName { get; set; }
        public string Data { get; set; }
    }
}