// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class Inventory
{
    public int StockTransactionID { get; set; }

    public int? LineID { get; set; }

    public int? PartID { get; set; }

    public int? JobID { get; set; }

    public int? ProductID { get; set; }

    public DateTime? DateStamp { get; set; }

    public string Note { get; set; }

    public string Description { get; set; }

    public int? UnitOfMeasureID { get; set; }

    public int? TransactionType { get; set; }

    public int? EmpID { get; set; }

    public decimal? InventoryAmount { get; set; }

    public int? LocationID { get; set; }

    public int? TransactionReference { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual Location Location { get; set; }

    public virtual TransActionType TransactionTypeNavigation { get; set; }

    public virtual UnitOfMeasure UnitOfMeasure { get; set; }
}