// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class Location
{
    public int LocationID { get; set; }

    public string LocationName { get; set; }

    public string Area { get; set; }

    public byte[] Photo { get; set; }

    public int? Aisle { get; set; }

    public string Row { get; set; }

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual ICollection<Part> Part { get; set; } = new List<Part>();
}