// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class OpCode
{
    public int OpCodeID { get; set; }

    public string OperationName { get; set; }
}