// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class OrderReciept
{
    public int OrderReceiptID { get; set; }

    public int? EmployeeID { get; set; }

    public int? PurchaseOrderID { get; set; }

    public DateTime? ReceiptDate { get; set; }

    public bool? IsOrderComplete { get; set; }

    public Employee Employee { get; set; }

    public PurchaseOrder PurchaseOrder { get; set; }

    public virtual ICollection<OrderReceiptItems> OrderReceiptItems { get; set; } = new List<OrderReceiptItems>();
}