// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class PartTypes
{
    public int PartTypeID { get; set; }

    public string PartTypeName { get; set; }

    public int? PartCategoryID { get; set; }

    public virtual PartCategory PartCategory { get; set; }
}