// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity
{
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            Attachment = new HashSet<Attachment>();
            OrderFee = new HashSet<OrderFee>();
            OrderReciept = new HashSet<OrderReciept>();
            PurchaseLineItem = new HashSet<PurchaseLineItem>();
        }

        public int PurchaseOrderID { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? ExpectedDate { get; set; }
        public int? SupplierID { get; set; }
        public int? EmployeeID { get; set; }
        public string SalesRep { get; set; }
        public int? JobID { get; set; }
        public bool? SuppressTax { get; set; }
        public int? ShipID { get; set; }
        public decimal? OrderTotal { get; set; }
        public bool? Recieved { get; set; }
        public decimal? ShippingCost { get; set; }
        public decimal? Tax { get; set; }
        public bool? IsBackOrder { get; set; }
        public DateTime? RecievedDate { get; set; }
        public decimal? SubTotal { get; set; }
        public string Memo { get; set; }
        public byte? OrderState { get; set; }
        public DateTime? DateAdded { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string AddedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string OrderFormat { get; set; }
        public double? TaxRate { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<OrderFee> OrderFee { get; set; }
        public virtual ICollection<OrderReciept> OrderReciept { get; set; }
        public virtual ICollection<PurchaseLineItem> PurchaseLineItem { get; set; }
    }
}