// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity
{
    public partial class ShipBy
    {
        public int ShipID { get; set; }
        public string ShipByName { get; set; }
    }
}