// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity
{
    public partial class Supplier
    {
        public Supplier()
        {
            PurchaseOrder = new HashSet<PurchaseOrder>();
        }

        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Zip { get; set; }
        public bool? Active { get; set; }
        public int? Category { get; set; }
        public int? AccountType { get; set; }
        public string AccountNumber { get; set; }
        public double? TaxRate { get; set; }

        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
    }
}