// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class ToolCheckOut
{
    public int ToolCheckoutID { get; set; }

    public int? EmpID { get; set; }

    public int? AssetID { get; set; }

    public DateTime? TimeStamp { get; set; }

    public int? DestinationID { get; set; }

    public bool? CheckedOut { get; set; }

    public bool? Lost { get; set; }
}