// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class TransActionType
{
    public int TransactionsTypeID { get; set; }

    public string TransactionTypeName { get; set; }

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();
}