// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class UnitOfMeasure
{
    public int UnitOfMeasureID { get; set; }

    public string UnitName { get; set; }

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual ICollection<OrderReceiptItems> OrderReceiptItems { get; set; } = new List<OrderReceiptItems>();

    public virtual ICollection<Part> Part { get; set; } = new List<Part>();

    public virtual ICollection<PurchaseLineItem> PurchaseLineItem { get; set; } = new List<PurchaseLineItem>();
}