// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Entity;

public partial class WorkCenter
{
    public int WorkCenterID { get; set; }

    public string WorkCenterName { get; set; }

    public decimal? CostRate { get; set; }

    public decimal? Availabilty { get; set; }
}